services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443" # HTTPS only
    volumes:
      - wp-volume:/var/www/html
    networks:
      - my-network
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - my-network
    restart: unless-stopped